# Generated by Django 6.0.5 on 2026-05-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('end_user', 'Citizen'), ('staff', 'Staff')], default='end_user', max_length=20),
        ),
    ]
