# Generated by Django 6.0.5 on 2026-06-09 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_flag_reason_profile_is_flagged_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='flag_reason',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_flagged',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phash_value',
        ),
    ]
