# Generated by Django 6.0.5 on 2026-07-07 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('motorcycle', 'Motorcycle'), ('car', 'Car'), ('jeep', 'Jeep'), ('truck', 'Truck'), ('bus', 'Bus'), ('other', 'Other')], max_length=20)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=50)),
                ('engine_number', models.CharField(max_length=100, unique=True)),
                ('chassis_number', models.CharField(max_length=100, unique=True)),
                ('registration_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('plate_number', models.CharField(help_text='Example: BA 2 PA 1234', max_length=20, unique=True)),
                ('vehicle_front_image', models.ImageField(upload_to='vehicles/front/')),
                ('vehicle_back_image', models.ImageField(blank=True, null=True, upload_to='vehicles/back/')),
                ('number_plate_image', models.ImageField(upload_to='vehicles/plate/')),
                ('bluebook_image', models.ImageField(upload_to='vehicles/bluebook/')),
                ('phash', models.CharField(blank=True, max_length=16)),
                ('dhash', models.CharField(blank=True, max_length=16)),
                ('fraud_score', models.FloatField(default=0)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('duplicate_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_matches', to='vehicles.vehicle')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_vehicles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('front', 'Front View'), ('back', 'Back View'), ('left', 'Left Side'), ('right', 'Right Side'), ('plate', 'Registration Plate'), ('bluebook', 'Bluebook')], max_length=20)),
                ('document_file', models.FileField(upload_to='vehicle_docs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vehicles.vehicle')),
            ],
        ),
    ]
