# Generated by Django 6.0.5 on 2026-06-10 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_registration_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='registration_number',
        ),
        migrations.RemoveField(
            model_name='vehicledocument',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='vehicledocument',
            name='remarks',
        ),
    ]
