# Generated by Django 6.0.5 on 2026-06-10 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_remove_vehicle_registration_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='registration_number',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='vehicledocument',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicledocument',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
