# Generated by Django 6.0.5 on 2026-07-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KycDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('citizenship', 'Citizenship Card'), ('driving_license', 'Driving License'), ('national_id', 'National ID')], max_length=20)),
                ('document_image', models.ImageField(upload_to='kyc_docs/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('ocr_raw_text', models.TextField(blank=True, null=True)),
                ('phash_value', models.CharField(blank=True, max_length=64, null=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('flag_reason', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
