# Generated by Django 6.0.5 on 2026-05-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycdocument',
            name='ocr_raw_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
