# Generated by Django 6.0.5 on 2026-06-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0002_kycdocument_ocr_raw_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycdocument',
            name='document_type',
            field=models.CharField(choices=[('citizenship', 'Citizenship Card'), ('driving_license', 'Driving License'), ('national_id', 'National ID')], max_length=20),
        ),
    ]
