# Generated by Django 6.0.5 on 2026-06-09 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0003_alter_kycdocument_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycdocument',
            name='flag_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kycdocument',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kycdocument',
            name='phash_value',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
